# Generated by Django 6.0.4 on 2026-04-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20)),
            ],
        ),
    ]
